swagger: "2.0"
info:
  version: "1.0.0"
  title: "gpt2-philosophical"
host: "master-gpt2-philosophical-ha-mulan.endpoint.ainize.ai"
basePath: "/api/"
schemes:
- "https"
- "http"
consumes:
  - string
produces:
  - string
paths:
  /:
    get:
      tags:
      - "generate philosophical script base on keyword"
      summary: "generate philosophical script base on keyword"
      description: 'please input keyword and you will find out philosophical script related to keyword.


      This app is generate answer in text form.


      How to use:


        First, input keyword.

        Second, wait for philosophical script related to keyword.


      '
      produces:
      - "string"
      - "application/xml"
      - "application/json"
      parameters:
      - name: "keyword"
        type: 'string'
        in: "query"
        description: "ex) type 'life'"
        required: true
        items:
          type: "string"
          default: "trump"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
